[workspace]
resolver = "3"
members = [
    "hello_rust",
    "hello_cargo", 
    "hello_dep_ran",
    "hello_sum_calc"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Torben Anderson"]
description = "Rust learning projects"
license = "MIT" 